# NumPy Programming Assignment

Part 1: Smart Array Factory
Task: Create a function that allows students to generate specific array types quickly using built-in NumPy methods.


In [5]:
import numpy as np

def array_factory(mode, shape, value=None):
    if mode == 'zeros':
        return np.zeros(shape) 
        
    elif mode == 'ones':
        return np.ones(shape)
        
    elif mode == 'full':
        return np.full(shape, value)
        
    elif mode == 'identity':
        return np.eye(shape[0])
    
    pass

    """
    Creates various NumPy arrays based on the mode.
    - 'zeros': Array filled with 0.
    - 'ones': Array filled with 1.
    - 'full': Array filled with a specified 'value'.
    - 'identity': A square identity matrix of size 'shape'.
    """
    # TODO: Students implement logic here
print("--- Zeros (2x3) ---")
print(array_factory('zeros', (2, 3)))

print("\n--- Ones (2x2) ---")
print(array_factory('ones', (2, 2)))

print("\n--- Full (3x3 filled with 7) ---")
print(array_factory('full', (3, 3), 7))

print("\n--- Identity (4x4) ---")
print(array_factory('identity', (4, 4)))
    
    

--- Zeros (2x3) ---
[[0. 0. 0.]
 [0. 0. 0.]]

--- Ones (2x2) ---
[[1. 1.]
 [1. 1.]]

--- Full (3x3 filled with 7) ---
[[7 7 7]
 [7 7 7]
 [7 7 7]]

--- Identity (4x4) ---
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Part 2: The secure_reshape_and_stack Function.

This function demonstrates how to handle data integration by transforming a flat data structure into a matrix and then combining it with an existing dataset

In [8]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    try:
        arr1 = np.array(data1)
        arr2 = np.array(data2)
        reshaped_arr1 = arr1.reshape(new_shape)
        combined_dataset = np.vstack((reshaped_arr1, arr2))
        return combined_dataset
    

    except ValueError as e:
        raise ValueError(f"Company-grade Error: {e}")
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.
    """
print("\n--- Secure Reshape and Stack ---")
data1 = [[1, 2, 3, 4], [5, 6, 7, 8]]
data2 = [[9, 10, 11, 12], [13, 14, 15, 16]]
print(secure_reshape_and_stack(data1, data2, (2, 4)))




--- Secure Reshape and Stack ---
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


part-3 The apply_threshold Function.

This function demonstrates Conditional Access and Modification, which are primarily used in data cleaning and processing. It follows the logic of identifying specific elements based on a boolean condition and replacing them efficiently.

In [9]:
import numpy as np

def apply_threshold(arr, threshold, replacement_value=-1):
    """
    Finds elements satisfying a condition (>= threshold) 
    and replaces them with a new value.
    """
    arr = np.array(arr)
    condition = arr >= threshold
    modified_arr = np.where(condition, replacement_value, arr)
    return modified_arr

TestCase

In [ ]:
branch_a = [1, 2, 3, 4, 5, 6] 

branch_b = [[7, 8, 9], 
            [10, 11, 12]]

final_report = secure_reshape_and_stack(branch_a, branch_b, (2, 3))

print(final_report)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
v= np.array([1,2,3])
apply_threshold(v,2,-20)


array([  1, -20, -20])