In [1]:
%pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 1.5 MB/s  0:00:10m0:00:0100:01
Note: you may need to restart the kernel to use updated packages.


In [13]:
import numpy as np
array = np.array([[1, 2, 3, 4, 5],[6,7,8,9,10]])
arr2ay = np.array([[1, 2, 3,8,9], [4, 5, 6,7,8]])
print("array1 ",array,type(array))
print(arr2ay)
print("-----------------")
print(array+arr2ay)
print(array.dot(arr2ay.T))
print(array*arr2ay)
print(array-arr2ay)
print(array/arr2ay)
#how can we know direction of vectors
print("-----------------")
print("shape of array1 ",array.shape)
age= [22, 35, 58, 45, 25]
age_array = np.array(age)
print("age array ",age_array)
print("shape of age array ",age_array.shape)

array1  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] <class 'numpy.ndarray'>
[[1 2 3 8 9]
 [4 5 6 7 8]]
-----------------
[[ 2  4  6 12 14]
 [10 12 14 16 18]]
[[ 91 100]
 [206 250]]
[[ 1  4  9 32 45]
 [24 35 48 63 80]]
[[ 0  0  0 -4 -4]
 [ 2  2  2  2  2]]
[[1.         1.         1.         0.5        0.55555556]
 [1.5        1.4        1.33333333 1.28571429 1.25      ]]
-----------------
shape of array1  (2, 5)
age array  [22 35 58 45 25]
shape of age array  (5,)


In [16]:
m1 = np.array([[1, 2, 3], [4, 5, 6], [5, 6, 7]])

m2 = np.array([[7, 8, 9], [10, 11, 12], [1, 2, 3]])

print("m1:\n", m1)
print("\n")
print("m2:\n", m2)

m1:
 [[1 2 3]
 [4 5 6]
 [5 6 7]]


m2:
 [[ 7  8  9]
 [10 11 12]
 [ 1  2  3]]


In [18]:
class person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
    def getinfo(self):
        return f"Name: {self.name}, Age: {self.age}"
p1 = person("Alice", 30)
p1.getinfo()

'Name: Alice, Age: 30'

In [19]:
m1.ndim

2

In [20]:
s= np.array(5)
s.shape
s.ndim

0

In [ ]:
import numpy as np

v1 = np.array([1, 2, 3, 4, 5, 6])
m1 = v1.reshape((3, 2))

print(v1)
print("==================")
print(v1.shape)
print(v1.shape[0])
#reshape
print("==================")
m1 = v1.reshape((3, 2))

[1 2 3 4 5 6]
(6,)
6


In [ ]:
import numpy as np

vec = np.array([1, 2, 3, 4])

# هنا بيستخدم (vec.shape[0]) عشان يعرف عدد العناصر لوحده
# ويحولها لعمود واحد (Column Vector)
mat = vec.reshape((vec.shape[0], 1))

print(mat)

In [ ]:
v1 = np.array([1, 2, 3, 4, 5, 6])
m1 = v1.reshape((3, 2))
# أو reshape((4, 1))
mat = v1.reshape((v1.shape[0], 1))
# أو reshape((4, 1))
mat = vec.reshape((vec.shape[0], 1))

In [27]:
m33 =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m33.dtype,m33)
m32 =np.array([[1.1,2,3],[4,5,6],[7,8,9]])
print(m32.dtype,m32)
m13 =np.array([[1,"2",3],[4,5,6],[7,8,9]])
print(m13.dtype,m13)
#any change in one element will change the whole array data type


int64 [[1 2 3]
 [4 5 6]
 [7 8 9]]
float64 [[1.1 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]
<U21 [['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]


NameError: name 'data' is not defined