In [16]:
import numpy as np
mat =np.zeros((3,3))    
m = np.ones((3,3))
ma= np.full((3,3),7)
maa= np.random.random((3,3))
mq= np.empty((3,3))
angle= np.arange(1,10,2)
V1= np.linspace(0,5,10)
S= np.identity(3)
a = ["a","b","c"]
q=np.random.choice(a,size=(3,5))
print(mat)
print("-----------------")
print(m)
print("-----------------")
print(ma)
print("-----------------")
print(maa)
print("-----------------")
print(mq)
print("-----------------")  
print(angle)
print("-----------------")
print(V1)
print("-----------------")
print(S)
print("-----------------")
print(q)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-----------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
-----------------
[[7 7 7]
 [7 7 7]
 [7 7 7]]
-----------------
[[0.21687562 0.09355178 0.4778665 ]
 [0.22477216 0.95565127 0.62994954]
 [0.79456413 0.78921303 0.9213575 ]]
-----------------
[[0.19655267 0.93707911 0.66097855]
 [0.15990046 0.46859006 0.12987659]
 [0.67304625 0.13981737 0.41029452]]
-----------------
[1 3 5 7 9]
-----------------
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
-----------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-----------------
[['c' 'a' 'c' 'b' 'a']
 ['b' 'a' 'b' 'b' 'c']
 ['b' 'a' 'b' 'a' 'b']]


In [17]:
m1t = np.ones((2,3))
mqs= np.ones((3,2))
np.savez('matrices.npz',m1t=m1t,mqs=mqs)
loaded = np.load('matrices.npz')
m1t_loaded = loaded['m1t']
mqs_loaded = loaded['mqs']
print("Loaded m1t:")
print(m1t_loaded)
print("Loaded mqs:")
print(mqs_loaded)


Loaded m1t:
[[1. 1. 1.]
 [1. 1. 1.]]
Loaded mqs:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np

# Create the arrays
mat_1 = np.ones((3, 4))
mat_2 = np.zeros((5, 3))

# Save the arrays into a zipped .npz file with specific keys
np.savez('test_save.npz', Ones_Mat=mat_1, Zeros_mat=mat_2)

# Load the file using a context manager and retrieve the arrays by key
with np.load('test_save.npz') as file:
    mat_1 = file['Ones_Mat']
    mat_2 = file['Zeros_mat']
    print("Matrix of Ones:")
    print(mat_1)
    print("Matrix of Zeros:")
    print(mat_2)
    

-----------------


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
m1 = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m2 = np.matrix([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
new_stack = np.vstack((m1, m2))
print("Vertically Stacked Matrix:")
print(new_stack)
new_stack = np.hstack((m1, m2))
print("Horizontally Stacked Matrix:")
print(new_stack)

Vertically Stacked Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [9 8 7]
 [6 5 4]
 [3 2 1]]
Horizontally Stacked Matrix:
[[1 2 3 9 8 7]
 [4 5 6 6 5 4]
 [7 8 9 3 2 1]]


In [30]:
s=1
v= np.array([1,2,3])
r = np.array([1,2,3,3,4])
s==v
s==r


array([ True, False, False, False, False])

In [31]:
v1 = np.array([1, 2, 3, 4, 10])
print(np.all(v1 > 2))

False


In [35]:
import numpy as np

v1 = np.array([1, 2, 3, 4, 10])
v2 = np.array([1, 2, 3, 5, 10])  # <--- This line was missing

print(np.any(v1 > 2))
np.isclose(v1, v2, atol=1)

True


array([ True,  True,  True,  True,  True])

In [ ]:
import numpy as np

# --- 1. Data Setup ---
# data_x: Your original dataset
data_x = np.array([10, 20, 20, 30, 40, 50, 60, 70, 80, 90])

# data_y: A second dataset required to calculate Covariance & Correlation
# I created this array to have a strong positive relationship with data_x
data_y = np.array([12, 22, 25, 35, 42, 55, 62, 75, 82, 95])

# --- 2. Descriptive Statistics (Single Variable) ---
mean_val = np.mean(data_x)
median_val = np.median(data_x)

# Mode: numpy has no direct mode function. 
# bincount() counts occurrences, argmax() finds the index of the highest count.
mode_val = np.bincount(data_x).argmax() 

# Variance & Standard Deviation
# ddof=0 is Population Variance (divide by N)
# ddof=1 is Sample Variance (divide by N-1) - Standard in research/statistics
variance = np.var(data_x, ddof=1)
std_dev = np.std(data_x, ddof=1)

min_val = np.min(data_x)
max_val = np.max(data_x)

# Percentiles: 25th (Q1), 50th (Median), 75th (Q3)
percentiles = np.percentile(data_x, [25, 50, 75])

# --- 3. Relationship Statistics (Two Variables) ---

# Covariance
# Returns a 2x2 matrix: [[var(x), cov(x,y)], [cov(y,x), var(y)]]
# We select [0,1] to get the covariance between x and y
cov_matrix = np.cov(data_x, data_y, ddof=1)
covariance_val = cov_matrix[0, 1]

# Correlation
# Returns a 2x2 matrix of correlation coefficients (r)
# r is always between -1 and 1
corr_matrix = np.corrcoef(data_x, data_y)
correlation_val = corr_matrix[0, 1]

# --- 4. Comparison (Fixing your NameError) ---
# np.isclose checks if two arrays are similar within a tolerance (atol)
# This is useful for cleaning data or comparing float values
are_close = np.isclose(data_x, data_y, atol=5) # Checks if they are within 5 units

# --- 5. Printing Results ---
print("--- DESCRIPTIVE STATISTICS (Data X) ---")
print(f"Mean:       {mean_val}")
print(f"Median:     {median_val}")
print(f"Mode:       {mode_val}")
print(f"Variance:   {variance:.2f}")
print(f"Std Dev:    {std_dev:.2f}")
print(f"Min/Max:    {min_val} / {max_val}")
print(f"Percentiles:{percentiles}")

print("\n--- RELATIONSHIP STATISTICS (X vs Y) ---")
print(f"Covariance:  {covariance_val:.2f}")
print(f"Correlation: {correlation_val:.4f}")

print("\n--- COMPARISON (isclose) ---")
print(f"Are X and Y within 5 units of each other?\n{are_close}")

NameError: name 'v2' is not defined

In [39]:
import numpy as np

# 1. DEFINE the variables first
v1 = np.array([10, 20, 20, 30, 40, 50, 60, 70, 80, 90])
v2 = np.array([15, 25, 10, 35, 45, 50, 70, 65, 85, 95])

# 2. NOW you can compare them
# This checks: Is v1 close to v2 (within a difference of 1)?
result = np.isclose(v1, v2, atol=1)

print("v1:", v1)
print("v2:", v2)
print("Are they close?", result)

v1: [10 20 20 30 40 50 60 70 80 90]
v2: [15 25 10 35 45 50 70 65 85 95]
Are they close? [False False False False False  True False False False False]


In [ ]:
%pip install pandas


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 1.4 MB/s  0:00:08m0:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [pandas]2m2/3 [pandas]
Note: you may need to restart the kernel to use updated packages.


In [42]:
import pandas as pd
s= pd.Series([10, 20, 30, 40, 50]) #series object matrix
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [43]:
p =pd.Series([5,10,15,20,25], index=['a','b','c','d','e'])
print(p)

a     5
b    10
c    15
d    20
e    25
dtype: int64


In [49]:
import pandas as pd

# 1. Create the data first
raw_data = [[1, 444, 'abc'],
            [2, 555, 'def'],
            [3, 666, 'ghi'],
            [4, 444, 'xyz'],
            [5, 555, 'ijk'],
            [6, 666, 'lmn']]

# 2. Define the DataFrame (I renamed 'Name' to 'info' to match your code)
data = pd.DataFrame(raw_data, columns=['ID', 'Code', 'info'])

# 3. Now you can convert the column to category
data["info"] = data['info'].astype("category")

# 4. Check the types and print the data
print(data.dtypes)
print("-" * 20)
print(data)

ID         int64
Code       int64
info    category
dtype: object
--------------------
   ID  Code info
0   1   444  abc
1   2   555  def
2   3   666  ghi
3   4   444  xyz
4   5   555  ijk
5   6   666  lmn


In [50]:
data["info"] = data['info'].astype("category")
data.dtypes

ID         int64
Code       int64
info    category
dtype: object

In [ ]:
data.head()

#first 5 rows
# can add number inside head() to get more rows like head(10)   

ID  Code info
0   1   444  abc
1   2   555  def
2   3   666  ghi
3   4   444  xyz
4   5   555  ijk

In [59]:
data.describe()


ID        Code
count  6.000000    6.000000
mean   3.500000  555.000000
std    1.870829   99.281418
min    1.000000  444.000000
25%    2.250000  471.750000
50%    3.500000  555.000000
75%    4.750000  638.250000
max    6.000000  666.000000

In [56]:
data.tail(2)

ID  Code info
4   5   555  ijk
5   6   666  lmn

In [60]:
data.columns

Index(['ID', 'Code', 'info'], dtype='object')

In [61]:
data['info'].unique()

['abc', 'def', 'ghi', 'xyz', 'ijk', 'lmn']
Categories (6, object): ['abc', 'def', 'ghi', 'ijk', 'lmn', 'xyz']

In [ ]:
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   ID      6 non-null      int64   
 1   Code    6 non-null      int64   
 2   info    6 non-null      category
dtypes: category(1), int64(2)
memory usage: 454.0 bytes


In [68]:
data.idxmax

<bound method DataFrame.idxmax of    ID  Code info
0   1   444  abc
1   2   555  def
2   3   666  ghi
3   4   444  xyz
4   5   555  ijk
5   6   666  lmn>

In [69]:
data['info'].iloc[2:3]

2    ghi
Name: info, dtype: category
Categories (6, object): ['abc', 'def', 'ghi', 'ijk', 'lmn', 'xyz']

In [75]:
# summation of previous column with new column
n = data['ID'] + data['Code']

data.insert(3,'new_info',n)



ValueError: cannot insert new_info, already exists

In [76]:
data.drop('new_info',axis=1)


ID  Code info
0   1   444  abc
1   2   555  def
2   3   666  ghi
3   4   444  xyz
4   5   555  ijk
5   6   666  lmn